# Generated by Django 5.2.9 on 2025-12-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('emailID', models.EmailField(blank=True, max_length=20, null=True, unique=True, verbose_name='Email ID')),
                ('emailID_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Email_ID Code')),
                ('country_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Country Code')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number')),
                ('phone_number_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone number Code')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('user_img', models.ImageField(blank=True, null=True, upload_to='Images/', verbose_name='User Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated DateTime')),
                ('last_logout_dt', models.DateTimeField(blank=True, null=True, verbose_name='Last_logout DateTime')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
